#!/bin/sh
# This script requires a clone of jsonpickle.github.com sibling to jsonpickle.
cd docs &&
rm -rf build &&
make html &&
rsync -avrP \
	--delete \
	--exclude=.git \
	--exclude=.gitignore \
	--exclude=.buildinfo \
	build/html/ ../../jsonpickle.github.com/
