name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Run ruff check 
        uses: astral-sh/ruff-action@v4
        with:
          args: "format --check --diff"

      - name: Run isort check
        uses: isort/isort-action@master
        with:
            configuration: "--check-only --diff --profile black"
